name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile and run test.cpp
      run: |
          g++ -std=c++11 test.cpp -o test
          ./test
    - name: Run tests
      run: |
          ./test --success
